version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: server-mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    restart: always

  php:
    build: ./docker/php
    container_name: server-php
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql
